import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-screen-2xl mx-auto px-4 bg-primary/20 grid place-content-center min-h-screen">
        {children}
      </body>
    </html>
  );
}
